server:
  port: 30145
  servlet:
    session:
      cookie:
        secure: false
        max-age: ${zkc.cookie-max-age-sec}
        http-only: true
        same-site: strict
        path: /
      timeout: 30m

mybatis:
  mapper-locations:
    - classpath*:mappers/*.xml
    - classpath*:**/mapper/common/*Mapper.xml
    - classpath*:**/mapper/embedded/*Mapper.xml
  config-location: classpath:jpaConfig-embedded.xml
mybatis-plus:
  mapper-locations: ${mybatis.mapper-locations}
  config-location: ${mybatis.config-location}

spring:
  application:
    name: h-zkc
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/message
    encoding: UTF-8
  mvc:
    interceptors:
      mdc:
        enabled: true
      api-safe:
        enabled: true
        include-path-patterns:
          - /hbq969-dict/**
          - /hbq969-tabula/**
        header-name: api-safe-token
        header-value-regex: 8DC75E91D4E143CF94BA29C46C43B24B
      resource-handler-registry:
        entries:
          - handlers: /hbq969-dict/**
            locations: classpath:/static/hbq969-dict/
          - handlers: /hbq969-tabula/**
            locations: classpath:/static/hbq969-tabula/
          - handlers: /hbq969-zkc/**
            locations: classpath:/static/hbq969-zkc/
        enabled: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      enabled: true
      base-packages: com.github.hbq969
      default-lookup-key: hikari
    hikari:
      jdbc-url: jdbc:h2:mem:local
      driver-class-name: org.h2.Driver
      username: foo
      password: ENC(2HRE3Jhuz6IfiD8L7orn4flpXNPTWLhH4u6lH/i0SWf8jXh3tNGQG++plhHmJN3F)
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
        port: ${server.port}
        tags: path=/${spring.application.name},port=${server.port},secure=false
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        health-check-path: /common/health
        health-check-interval: 10s
      host: localhost
      port: 8500

knife4j:
  enable: false
  production: false
  basic:
    enable: false
    username: ${spring.application.name}
    password: 123456

swagger:
  base-package: com
  api-info:
    title: web应用Restful API
    description: web应用Restful API
    termsOfServiceUrl: http://127.0.0.1:${server.port}
    version: v1.0
    license: Apache LICENSE-2.0
    licenseUrl: https://apache.org/licenses/LICENSE-2.0.txt

dict:
  enabled: true
  reload:
    cron: 0 */30 * * * *
  map-key-prefix: fmt

encrypt:
  config:
    enabled: true
  restful:
    enabled: true
    aes:
      key: DC2EE8931E434A44
      show-log: true

advice:
  log:
    enabled: true
  restful-limit:
    enabled: true

tabula:
  enabled: true
  dialect: mysql
  schema: workbench
  open-edit-delete: true

zkc:
  urls: docker.for.mac.host.internal:22181
  connect-timeout-mills: 5000
  dialect: embedded
  user: foo
  pwd: bar
  exclude-urls:
    - "/**/*.js"
    - "/**/*.css"
    - "/**/*.png"
    - "/**/*.jpg"
    - "/**/*.map"
    - "/**/*.html"
    - "/**/*.ico"
    - "/**/login"
    - "/**/logout"
    - "/**/error"
    - "/**/health"
  cookie-max-age-sec: 1800
  enable-write-acl: false