apiVersion: v1
kind: Service
metadata:
  name: h-zkc
  namespace: ${k8s_ns}
  labels:
    app: h-zkc
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 30145
      targetPort: 30145
      protocol: TCP
      name: restful
  selector:
    app: h-zkc

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: h-zkc-deployment
  namespace: ${k8s_ns}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: h-zkc
  template:
    metadata:
      labels:
        name: h-zkc
        app: h-zkc
    spec:
      restartPolicy: Always
      volumes:
        - name: app-logs
          hostPath:
            path: /tmp/apps/h-zkc/logs
      containers:
        - name: h-zkc
          image: ${docker_prefix}/h-zkc:${tag}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 30145
              path: /common/health
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          readinessProbe:
            httpGet:
              port: 30145
              path: /common/health
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          resources:
            requests:
              cpu: '1'
              memory: 1Gi
            limits:
              cpu: '1'
              memory: 1.5Gi
          volumeMounts:
            - mountPath: /opt/app/h-zkc/logs
              name: app-logs
          ports:
            - containerPort: 30145
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "false"
            - name: spring_cloud_zookeeper_connectString
              value: ""
            - name: spring_cloud_zookeeper_auth_info
              value: ""
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

